JIRA: ABC-171 Automatically resize Alembic clips to the animation length on creation
Unity-Technologies/com.unity.formats.alembic pull request #451
Opened 2021-06-21 17:36 UTC by clusty

When dragging an alembic stream player onto a timeline alembic track, the length of the clip should be the same as a the StreamPlayer's duration:

@cguer strange cases to test:
* Duplicate a clip should preserve source length.
* Focus clip in Timeline asset mode 
* Drag a clip that has only 1 frame
* Test mechanism when inside subtimelines.

2021-07-13 17:22 UTC, cguer requested changes
Already discussed with Vlad in person but adding here for history:

Everything looks good to me except when the Alembic file only has 1 sample. It creates a tiny clip that is hard to manipulate and we can assume such "static" meshes would usually be used for longer.
To avoid this, we'll fallback to the default clip length (5s) if the Alembic file only has one frame/sample.

2021-07-13 20:15 UTC, cguer approved these changes
QA approved 👍!

Tested on:
- 2021.2.0b2 (Windows only)

2021-07-15 15:10 UTC, sebastienduverne approved these changes
Changelog OK

2021-07-20 14:43 UTC, judubu approved these changes

2021-07-20 17:19 UTC, merged