Add missing HDCamera/UniversalCamera component (ABC-362)
Unity-Technologies/com.unity.formats.alembic pull request #527
Opened 2023-02-06 13:53 UTC by thomas-tu

# Purpose of this PR:

Imported Cameras from Alembic don't have the additional components HDRP and URP use. They have to be manually added to fully work with their respective rendering pipeline.

#Testing

Added an automatic test with an asset from @cguer for HDRP and URP.

2023-02-06 14:56 UTC, RoseHirigoyen approved these changes

2023-02-15 21:53 UTC, arejayelle approved these changes

2023-02-16 19:44 UTC, cguer approved these changes
QA approved 👍!

Tested on:
- 2023.1.0b2 (Windows only, HDRP + URP + Legacy)

2023-02-17 10:48 UTC, lucillecaillaud reviewed
Code looks good to me!

Waiting on more info on [this thread](https://unity.slack.com/archives/C026KK6FCMB/p1676301354805589) to validate that it's the correct way to fix the issue.

Even though the problem is only reproducible with the "solutions recorder" it still sounds correct that when you import an Alembic in Unity it's correct straight away.

The only potential problem I'd see to that would be that it could impact import performances. But the difference is so small, I'm not sure how it could be noticeable.

2023-02-21 14:05 UTC, lucillecaillaud approved these changes

2023-02-21 15:01 UTC, MaryPerchanok requested changes

2023-02-21 15:03 UTC, MaryPerchanok requested changes

2023-02-21 15:03 UTC, MaryPerchanok commented on com.unity.formats.alembic/CHANGELOG.md
> +- Comform the GameObject cameras to these rendering pipelines with the additional data at import time.
Suggestion:

- At import, additional data is added to GameObject cameras to conform with URP or HDRP rendering pipelines.

2023-02-21 18:48 UTC, MaryPerchanok approved these changes
Approved!

2023-02-21 18:55 UTC, merged